<?php
/**
 * @category   Indglobal
 * @package    Indglobal_Measurementform
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Indglobal\Measurementform\Controller\Index;

use Magento\Framework\App\Action\Context;
use Indglobal\Measurementform\Model\MeasurementformFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Measurementform
     */
    protected $_measurementform;

    public function __construct(
		Context $context,
        MeasurementformFactory $measurementform
    ) {
        $this->_measurementform = $measurementform;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$measurementform = $this->_measurementform->create();
        $measurementform->setData($data);
        if($measurementform->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('measurementform/index/index');
        return $resultRedirect;
    }
}
