<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Gownmeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Gownmeasurement\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context, 
        \Magento\Framework\Registry $registry, 
        \Magento\Framework\Data\FormFactory $formFactory,  
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig, 
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_varsidhi_gownmeasurement_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('gownmeasurement_id', 'hidden', ['name' => 'gownmeasurement_id']);
        }
        $fieldset->addField(
            'name',
            'text',
            ['name' => 'name', 'label' => __('Name'), 'title' => __('Name'), 'required' => true]
        );
        $fieldset->addField(
            'email',
            'text',
            ['name' => 'email', 'label' => __('Email'), 'title' => __('Email'), 'required' => true]
        );
        $fieldset->addField(
            'contactno',
            'text',
            ['name' => 'contactno', 'label' => __('Contact No'), 'title' => __('Contact No'), 'required' => true]
        );
        $fieldset->addField(
            'orderid',
            'text',
            ['name' => 'orderid', 'label' => __('Order Id'), 'title' => __('Order Id'), 'required' => false]
        );
        $fieldset->addField(
            'shoulder',
            'text',
            ['name' => 'shoulder', 'label' => __('Shoulder'), 'title' => __('Shoulder'), 'required' => true]
        );
        $fieldset->addField(
            'bust_chest',
            'text',
            ['name' => 'bust_chest', 'label' => __('Bust/Chest (around)'), 'title' => __('Bust/Chest (around)'), 'required' => true]
        );
        $fieldset->addField(
            'waist',
            'text',
            ['name' => 'waist', 'label' => __('Waist'), 'title' => __('Waist'), 'required' => true]
        );
        $fieldset->addField(
            'hip',
            'text',
            ['name' => 'hip', 'label' => __('Hip'), 'title' => __('Hip'), 'required' => true]
        );
        $fieldset->addField(
            'sleeves',
            'text',
            ['name' => 'sleeves', 'label' => __('Sleeves (around)'), 'title' => __('Sleeves (around)'), 'required' => true]
        );
        $fieldset->addField(
            'armhole',
            'text',
            ['name' => 'armhole', 'label' => __('Arm Hole (around)'), 'title' => __('rm Hole (around)'), 'required' => true]
        );
        $fieldset->addField(
            'arm',
            'text',
            ['name' => 'arm', 'label' => __('Arm (around)'), 'title' => __('Arm (around)'), 'required' => true]
        );
        $fieldset->addField(
            'kameez_length',
            'text',
            ['name' => 'kameez_length', 'label' => __('Kameez (length)'), 'title' => __('Kameez (length)'), 'required' => true]
        );
        $fieldset->addField(
            'lower_waist',
            'text',
            ['name' => 'lower_waist', 'label' => __('Lower Waist (around)'), 'title' => __('Lower Waist (around)'), 'required' => true]
        );
        $fieldset->addField(
            'image',
            'image',
            [
                'name' => 'image',
                'label' => __('Image'),
                'title' => __('Image'),
                'required'  => false
            ]
        );
        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
        $fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );
        
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
