<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Blousemeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Blousemeasurement\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context, 
        \Magento\Framework\Registry $registry, 
        \Magento\Framework\Data\FormFactory $formFactory,  
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig, 
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_varsidhi_blousemeasurement_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('blousemeasurement_id', 'hidden', ['name' => 'blousemeasurement_id']);
        }
        $fieldset->addField(
            'name',
            'text',
            ['name' => 'name', 'label' => __('Name'), 'title' => __('Name'), 'required' => true]
        );
        $fieldset->addField(
            'email',
            'text',
            ['name' => 'email', 'label' => __('Email'), 'title' => __('Email'), 'required' => true]
        );
        $fieldset->addField(
            'contactno',
            'text',
            ['name' => 'contactno', 'label' => __('Contact No'), 'title' => __('Contact No'), 'required' => true]
        );
        $fieldset->addField(
            'orderid',
            'text',
            ['name' => 'orderid', 'label' => __('Order Id'), 'title' => __('Order Id'), 'required' => false]
        );
        $fieldset->addField(
            'size',
            'text',
            ['name' => 'size', 'label' => __('Size'), 'title' => __('Size'), 'required' => true]
        );
        $fieldset->addField(
            'unit',
            'text',
            ['name' => 'unit', 'label' => __('Unit'), 'title' => __('Unit'), 'required' => true]
        );
        $fieldset->addField(
            'blouse_opening',
            'text',
            ['name' => 'blouse_opening', 'label' => __('Blouse Opening'), 'title' => __('Blouse Opening'), 'required' => true]
        );
        $fieldset->addField(
            'cups',
            'text',
            ['name' => 'cups', 'label' => __('Cups'), 'title' => __('Cups'), 'required' => true]
        );
        $fieldset->addField(
            'neck_shoulder',
            'text',
            ['name' => 'neck_shoulder', 'label' => __('Neck Shoulder'), 'title' => __('Neck Shoulder'), 'required' => true]
        );
        $fieldset->addField(
            'full_shoulder',
            'text',
            ['name' => 'full_shoulder', 'label' => __('Full Shoulder'), 'title' => __('Full Shoulder'), 'required' => true]
        );
        $fieldset->addField(
            'neck_style',
            'text',
            ['name' => 'neck_style', 'label' => __('Neck Style'), 'title' => __('Neck Style'), 'required' => true]
        );
        $fieldset->addField(
            'sleeve',
            'text',
            ['name' => 'sleeve', 'label' => __('Sleeve'), 'title' => __('Sleeve'), 'required' => true]
        );
        $fieldset->addField(
            'sleeve_circumference',
            'text',
            ['name' => 'sleeve_circumference', 'label' => __('Sleeve Circumference'), 'title' => __('Sleeve Circumference'), 'required' => true]
        );
        $fieldset->addField(
            'waist_midriff',
            'text',
            ['name' => 'waist_midriff', 'label' => __('Waist Midriff (around)'), 'title' => __('Waist Midriff (around)'), 'required' => true]
        );
        $fieldset->addField(
            'blouse_length',
            'text',
            ['name' => 'blouse_length', 'label' => __('Blouse (Length)'), 'title' => __('Blouse (Length)'), 'required' => true]
        );
        $fieldset->addField(
            'front_neck',
            'text',
            ['name' => 'front_neck', 'label' => __('Front Neck (depth)'), 'title' => __('Front Neck (depth)'), 'required' => true]
        );
        $fieldset->addField(
            'front_cross',
            'text',
            ['name' => 'front_cross', 'label' => __('Front Cross'), 'title' => __('Front Cross'), 'required' => true]
        );
        $fieldset->addField(
            'bust_chest',
            'text',
            ['name' => 'bust_chest', 'label' => __('Bust/Chest (around)'), 'title' => __('Bust/Chest (around)'), 'required' => true]
        );
        $fieldset->addField(
            'shoulder_to_apex',
            'text',
            ['name' => 'shoulder_to_apex', 'label' => __('Shoulder to Apex'), 'title' => __('Shoulder to Apex'), 'required' => true]
        );
        $fieldset->addField(
            'arm_hole',
            'text',
            ['name' => 'arm_hole', 'label' => __('Arm Hole (around)'), 'title' => __('Arm Hole (around)'), 'required' => true]
        );
        $fieldset->addField(
            'specials',
            'editor',
            [
                'name' => 'specials',
                'label' => __('Specials'),
                'title' => __('Specials'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );
        $fieldset->addField(
            'image',
            'image',
            [
                'name' => 'image',
                'label' => __('Image'),
                'title' => __('Image'),
                'required'  => false
            ]
        );
        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
        $fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );
        
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
