<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Salwarmeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Salwarmeasurement\Model\ResourceModel;

class Salwarmeasurement extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('varsidhi_salwarmeasurement', 'salwarmeasurement_id');   //here "varsidhi_salwarmeasurement" is table name and "salwarmeasurement_id" is the primary key of custom table
    }
}