<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Gownmeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Gownmeasurement\Controller\Index;

use Magento\Framework\App\Action\Context;
use Varsidhi\Gownmeasurement\Model\GownmeasurementFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Gownmeasurement
     */
    protected $_gownmeasurement;

    public function __construct(
		Context $context,
        GownmeasurementFactory $gownmeasurement
    ) {
        $this->_gownmeasurement = $gownmeasurement;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$gownmeasurement = $this->_gownmeasurement->create();
        $gownmeasurement->setData($data);
        if($gownmeasurement->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('gownmeasurement/index/index');
        return $resultRedirect;
    }
}
