<?php

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();

$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<div class="header-custom-links">
	<a href="<?php echo $this->getBaseUrl().'varsidhi-virtual-payments.html' ?>"><img src="<?php echo $mediaUrl.'/virtual-payment.png'?>">Virtual Payment</a>
	<a href="<?php echo $this->getBaseUrl().'video-shopping' ?>"><img src="<?php echo $mediaUrl.'/video.png'?>"> Video Shopping</a>
	<a href="https://api.whatsapp.com/send?phone=919962241000"><img src="<?php echo $mediaUrl.'/whatsapp.png'?>"> +91-9962241000</a>
</div>






<script type="text/javascript">
	require(['jquery'], function(jQuery){
		jQuery(document).ready(function(){
			var Accordion = function(el, multiple) {
				this.el = el || {};
				this.multiple = multiple || false;

				var links = this.el.find('.article-title');
				links.on('click', {
						el: this.el,
						multiple: this.multiple
				}, this.dropdown)
			}

			Accordion.prototype.dropdown = function(e) {
					var $el = e.data.el;
					$this = jQuery(this),
							$next = $this.next();

					$next.slideToggle();
					$this.parent().toggleClass('open');

					if (!e.data.multiple) {
							$el.find('.accordion-content').not($next).slideUp().parent().removeClass('open');
					};
			}
			var accordion = new Accordion(jQuery('.accordion-container'), false);
	});

	jQuery(document).on('click', function (event) {
	  if (!jQuery(event.target).closest('#accordion').length) {
	    jQuery(this).parent().toggleClass('open');
	  }
		})
	});
</script>