<?php
/**
 * Copyright © 2018 Ideo. All rights reserved.
 * @license GPLv3
 */

/**
 * @var \Ideo\StoreLocator\Block\Html\Link $block
 */

// @codingStandardsIgnoreFile
?>
<li class="level0 level-top<?php if($block->isCurrent()) echo ' active'; ?>">
    <a href="<?php echo $block->getHref(); ?>" title="<?php echo $block->escapeHtml($block->getLabel()); ?>" class="level-top">
        <?php echo $block->escapeHtml($block->getLabel()); ?>
    </a>
</li>