<style type="text/css">
	.pr-static-links a
	{
		font-size: 16px;
		padding: 20px;
		text-align: center;
	}
</style>
<div class="container pr-static-links"><a href="/faq" class="">FAQ</a> <!--<a href="/shipping-policy" class="">Free Shipping</a>--> <a href="/terms-conditions" class="">Terms and Conditions</a> <a href="/return-and-refund-policy" class="">Shipping and Return Policies</a> <a href="/cash-on-delivery" class="">Cash on Delivery</a> <a href="/fabrics-care" class="">Fabrics Care</a></div>