<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php $estDelivery = $_product->getResource()->getAttribute('estimated_delivery')->getFrontend()->getValue($_product); 
  if($estDelivery != ''){ ?>
  <p class='estd-label' style="color:#006400; font-size: 14px; font-weight: 500;">Estimated Delivery Date: <?php echo $estDelivery ?></p>
<?php } ?>

<?php if ($_attributeValue): ?>
<div class="product attibute <?php /* @escapeNotVerified */ echo $_className?>">
    <?php if ($_attributeLabel != 'none'): ?>
    <div class="title" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass":"hidden", "toggleContainers":"#short_description_content"}}'>
	    <strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong>
    </div>
    <?php endif; ?>    
    <div id="short_description_content" class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
</div>
<?php endif; ?>

<div class='custom-info'>
  <div class="row">
    <div class="col-md-6" style="width: 50%;">
      <p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> Assuered Quality</p>
      <p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> Best Price</p>
      <p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> 100% Purchase Protection</p>
    </div>
    <div class="col-md-6" style="width: 50%;">
      <p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> 90% Ready to Ship</p>
      <!--<p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> Free Shipping Worldwide</p>-->
      <p class="item"><i class="fa fa-check-square-o" aria-hidden="true"></i> Custom Fit</p>
    </div>   
  </div>
</div>

