<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Lehengameasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Lehengameasurement\Model\ResourceModel\Lehengameasurement;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'lehengameasurement_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Varsidhi\Lehengameasurement\Model\Lehengameasurement',
            'Varsidhi\Lehengameasurement\Model\ResourceModel\Lehengameasurement'
        );
    }
}