<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Videoshopping
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Videoshopping\Controller\Index;

use Magento\Framework\App\Action\Context;
use Varsidhi\Videoshopping\Model\VideoshoppingFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Videoshopping
     */
    protected $_videoshopping;

    public function __construct(
		Context $context,
        VideoshoppingFactory $videoshopping
    ) {
        $this->_videoshopping = $videoshopping;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$videoshopping = $this->_videoshopping->create();
        $videoshopping->setData($data);
        if($videoshopping->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('video-shopping');
        return $resultRedirect;
    }
}
