<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\Link $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<li class="link my-account-link custom-class">
	<a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <img src="<?php echo $block->getBaseUrl() ?>media/header/my-account.svg" alt="<?= $escaper->escapeHtml($block->getLabel()) ?>" class="my-account-icon" />
        <?php //$escaper->escapeHtml($block->getLabel()) ?>
    </a>
</li>
