<div class="all-template-content">
	<div class="template-item">
    	<h2><?php echo __('BLACK FRIDAY')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template1.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('CHRISTMAS')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template2.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('DESIGN')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template3.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('HALLOWEEN')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template4.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('NEW YEAR')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template5.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('THANKS GIVING')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template6.png'); ?>" />
    </div>
    <div class="template-item">
    	<h2><?php echo __('VALENTINE DAY')?></h2>
        <img src="<?php echo $this->getViewFileUrl('Magecomp_Recentsalesnotification::images/template7.png'); ?>" />
    </div>
</div>
<style>
.all-template-content {
  float: left;
  width: 100%;
}
.template-item {
  border-bottom: 3px solid;
  float: left;
  padding-bottom: 15px;
  width: 100%;
}
.template-item h2 {
  margin: 10px 0;
}
.template-item > img {
  float: left;
  width: 100%;
}
</style>