<?php
/**
 * @category   Indglobal
 * @package    Indglobal_Measurementform
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Indglobal\Measurementform\Model\ResourceModel;

class Measurementform extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('indglobal_measurementform', 'measurementform_id');   //here "indglobal_measurementform" is table name and "measurementform_id" is the primary key of custom table
    }
}