<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Salwarmeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Salwarmeasurement\Controller\Index;

use Magento\Framework\App\Action\Context;
use Varsidhi\Salwarmeasurement\Model\SalwarmeasurementFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Salwarmeasurement
     */
    protected $_salwarmeasurement;

    public function __construct(
		Context $context,
        SalwarmeasurementFactory $salwarmeasurement
    ) {
        $this->_salwarmeasurement = $salwarmeasurement;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$salwarmeasurement = $this->_salwarmeasurement->create();
        $salwarmeasurement->setData($data);
        if($salwarmeasurement->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('salwarmeasurement/index/index');
        return $resultRedirect;
    }
}
