<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Lehengameasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Lehengameasurement\Controller\Index;

use Magento\Framework\App\Action\Context;
use Varsidhi\Lehengameasurement\Model\LehengameasurementFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Lehengameasurement
     */
    protected $_lehengameasurement;

    public function __construct(
		Context $context,
        LehengameasurementFactory $lehengameasurement
    ) {
        $this->_lehengameasurement = $lehengameasurement;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$lehengameasurement = $this->_lehengameasurement->create();
        $lehengameasurement->setData($data);
        if($lehengameasurement->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('lehengameasurement/index/index');
        return $resultRedirect;
    }
}
