<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Blousemeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Blousemeasurement\Controller\Index;

use Magento\Framework\App\Action\Context;
use Varsidhi\Blousemeasurement\Model\BlousemeasurementFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Blousemeasurement
     */
    protected $_blousemeasurement;

    public function __construct(
		Context $context,
        BlousemeasurementFactory $blousemeasurement
    ) {
        $this->_blousemeasurement = $blousemeasurement;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$blousemeasurement = $this->_blousemeasurement->create();
        $blousemeasurement->setData($data);
        if($blousemeasurement->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('blousemeasurement/index/index');
        return $resultRedirect;
    }
}
