<?php
/**
 * @category   Indglobal
 * @package    Indglobal_Measurementform
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Indglobal\Measurementform\Model\ResourceModel\Measurementform;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'measurementform_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Indglobal\Measurementform\Model\Measurementform',
            'Indglobal\Measurementform\Model\ResourceModel\Measurementform'
        );
    }
}