<?php
/**
 * @category   Varsidhi
 * @package    Varsidhi_Gownmeasurement
 * @author     developer18@indglobal-consulting.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Varsidhi\Gownmeasurement\Model\ResourceModel;

class Gownmeasurement extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('varsidhi_gownmeasurement', 'gownmeasurement_id');   //here "varsidhi_gownmeasurement" is table name and "gownmeasurement_id" is the primary key of custom table
    }
}