<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>

<?php
$storeUrls = $block->getViewModel()->getStoreUrls();
$baseUrl = $storeUrls['base'];
$mediaUrl = $storeUrls['media'];
$staticUrl = $storeUrls['static'];
?>

<script data-rocketjavascript="false">
    var MagefanWebP = {

        _canUseWebP: null,

        getUserAgentInfo: function(){
            try {
                var ua = navigator.userAgent,
                    tem,
                    M = ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) || [];
                if (/trident/i.test(M[1])) {
                    tem = /\brv[ :]+(\d+)/g.exec(ua) || [];
                    return ['IE', (tem[1] || '')];
                }
                if (M[1] === 'Chrome') {
                    tem = ua.match(/\b(OPR|Edge)\/(\d+)/);
                    if (tem != null) {
                        tem = tem.slice(1);
                        tem[0] = tem[0].replace('OPR', 'Opera');
                        return tem;
                    }
                }
                M = M[2] ? [M[1], M[2]] : [navigator.appName, navigator.appVersion, '-?'];
                if ((tem = ua.match(/version\/(\d+)/i)) != null) M.splice(1, 1, tem[1]);
                return M;
            } catch (e) {
                return ['', 0];
            }
        },

        canUseWebP: function(){

            if (null !== this._canUseWebP){
                return this._canUseWebP;
            }

            try {
                var elem = document.createElement('canvas');
                if (!!(elem.getContext && elem.getContext('2d'))) {
                    var r = (elem.toDataURL('image/webp').indexOf('data:image/webp') == 0);
                    if (!r) {
                        var ua = this.getUserAgentInfo();
                        if (ua && ua.length > 1) {
                            ua[0] = ua[0].toLowerCase();
                            if ('firefox' == ua[0] && parseInt(ua[1]) >= 65) {
                                this._canUseWebP = true;
                                return this._canUseWebP;
                            }
                            if ('edge' == ua[0] && parseInt(ua[1]) >= 18) {
                                this._canUseWebP = true;
                                return this._canUseWebP;
                            }
                            if ('safari' == ua[0] && parseInt(ua[1]) >= 15) {
                                this._canUseWebP = true;
                                return this._canUseWebP;
                            }
                        }
                    }

                    this._canUseWebP = r;
                    return this._canUseWebP;
                }
                this._canUseWebP = false;
                return this._canUseWebP;
            } catch (e) {
                console.log(e);
                this._canUseWebP = false;
                return this._canUseWebP;
            }
        },

        getOriginWebPImage: function(src) {

            if (src.indexOf('mf_webp') == -1) {
                return src;
            }

            var $array = src.split('/');
            var $imageFormat = '';

            for (var i = 0; i < $array.length; i++) {
                if ($array[i] == "mf_webp") {
                    $imageFormat = $array[i + 1];
                    $array.splice(i, 3);
                    break;
                }
            }
            src = $array.join('/');
            return src.replace('.webp', '.' + $imageFormat);
        },

        getWebUrl: function (imageUrl) {
            /* @var string */
            imageUrl = imageUrl.trim();
            var baseUrl = '<?= $baseUrl ?>';
            var imageFormat = imageUrl.split('.').pop();
            var mediaBaseUrl = '<?= $mediaUrl ?>';
            var staticBaseUrl = '<?=$staticUrl ?>';

            if (imageUrl.indexOf(mediaBaseUrl) == -1 && imageUrl.indexOf(staticBaseUrl) == -1) {
                return false;
            }

            var imagePath = imageUrl;
            imagePath = imagePath.replace(mediaBaseUrl, 'media/');
            imagePath = imagePath.replace(staticBaseUrl, 'static/');
            imagePath = imagePath.replace(baseUrl + 'pub/media/', 'media/');
            imagePath = imagePath.replace(baseUrl + 'pub/static/', 'static/');
            imagePath = imagePath.replace(/\.(jpg|jpeg|png|JPG|JPEG|PNG|gif|GIF)/i, '.webp');
            imagePath = mediaBaseUrl + 'mf_webp/' + imageFormat + '/' + imagePath;
            imagePath = imagePath.replace('%20', ' ');
            imagePath = imagePath.replace(/version\d{10}\//g, '');
            return imagePath;
        }
    };

    /* MagicToolboxContainer Fix */
    function MagefanWebPMagicToolboxContainerFix()
    {
        if (!MagefanWebP.canUseWebP()) {
            (function(){
                var i;
                var els = document.querySelectorAll(".MagicToolboxContainer a, .MagicToolboxContainer img");
                if (!els) return;
                var el;
                for (i=0; i<els.length; i++) {
                    el = els[i];
                    if (el.href) {
                        el.href = MagefanWebP.getOriginWebPImage(el.href);
                    }

                    if (el.getAttribute('webpimg')) {
                        el.src = MagefanWebP.getOriginWebPImage(el.getAttribute('webpimg'));
                    } else {
                        if (el.src) {
                            el.src = MagefanWebP.getOriginWebPImage(el.src);
                        }
                    }

                    if (el.dataset && el.dataset.image) {
                        el.dataset.image = MagefanWebP.getOriginWebPImage(el.dataset.image);
                    }

                }
            })();
        } else {
            replacePixelMagicToolbox();
            checkIfPixelReplaced();
        }
    }

    function replacePixelMagicToolbox() {
        (function() {
            var i, els = document.querySelectorAll(".MagicToolboxContainer img");

            if (!els) return;
            var el;

            for (i=0; i<els.length; i++) {
                el = els[i];

                if (el.getAttribute('webpimg')) {
                    el.src = el.getAttribute('webpimg');
                }
            }
        })();
    }

    function checkIfPixelReplaced() {
        var intervalCounter = 0,
            waitForMagicToolbox = setInterval(function() {
                if (document.querySelectorAll('figure img[src$="/p.jpg"]').length) {
                    replacePixelMagicToolbox();
                    clearInterval(waitForMagicToolbox);
                }

                if (intervalCounter > 10) {
                    clearInterval(waitForMagicToolbox);
                }

                intervalCounter++;
            }, 500);
    }

    document.addEventListener("DOMContentLoaded", function(){
        if (!MagefanWebP.canUseWebP()) {
            document.body.className += ' no-webp ';

            (function(){
                var i;
                var els = document.querySelectorAll('a[href$=".webp"]');
                if (!els) return;
                var el;
                for (i=0; i<els.length; i++) {
                    el = els[i];
                    if (el.href) {
                        el.href = MagefanWebP.getOriginWebPImage(el.href);
                    }
                }
            })();

        } else {
            document.body.className += ' webp-supported ';
        }
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function(e){
        if (!MagefanWebP.canUseWebP()) {
            /* Replace some custom webp images with original one if webp is not supported */
            /* Can add <a> tag in future as well */
            setInterval(function(){
                document.querySelectorAll("img[src$='.webp']:not(.no-origin-webp-img)").forEach(function(el){
                    var scr = el.getAttribute('src');
                    var newScr = MagefanWebP.getOriginWebPImage(scr);

                    if (scr != newScr) {
                        el.setAttribute('src', newScr);
                    } else {
                        el.classList.add('no-origin-webp-img');
                    }
                });

            }, 1000);
        }

        function processLazyPictureImg(img)
        {
            var src = img.getAttribute('src');
            var keys = ['original', 'src', 'lazyload'];
            var original, _original;
            for (var i=0;i<keys.length;i++) {
                _original = img.getAttribute('data-' + keys[i]);
                if (_original) {
                    original = _original;
                    break;
                }
            }
            if (original == src) {

                if (img.getAttribute('data-mf-lazy-picture-img')) return;
                img.setAttribute('data-mf-lazy-picture-img', 1);


                img.parentElement.querySelectorAll('source').forEach(function(el){
                    var srcset = el.getAttribute('srcset');
                    var originalset = el.getAttribute('data-originalset');
                    if (originalset && (originalset != srcset)) {
                        el.setAttribute('srcset', originalset);
                        el.classList.remove('lazyload');
                    }
                });

                var lazyLoader = img.closest('.lazy-loader');
                if (lazyLoader) {
                    lazyLoader.classList.remove('lazy-loader');
                }

                document.querySelectorAll("picture img[src='"+src+"']").forEach(function(img){
                    processLazyPictureImg(img);
                });

            }
        }

        document.querySelectorAll('picture img[data-original],picture img[data-src],picture img[data-lazyload]').forEach(function(el){
            el.addEventListener('load', function(e){
                processLazyPictureImg(e.target);
            });
            processLazyPictureImg(el);
        });
    });
</script>
<style>
    picture.mfwebp source.lazyload,
    picture.mfwebp source.lazy {background:none;content:none;}
</style>
