<?php
/** @var \Varsidhi\CategoryGrid\Block\CategoryGrid $block */
$categories = $block->getCategoryData();
$title = $block->escapeHtml($block->getData('title'));
$subTitle = $block->escapeHtml($block->getData('subtitle'));
?>

<?php if (!empty($categories)): ?>
<section class="category-grid-section">
    <div class="category-header">
        <div class="title"><h2><?= $title?></h2></div>
        <div class="subtitle"><p><?= $subTitle?></p></div>
        <div class="divider"><img src="<?= $block->getViewFileUrl('Varsidhi_CategoryGrid::images/icon/horizontal-devider.svg') ?>" alt="divider"></div>
    </div>
    <div class="container">
        <div class="category-grid">
        <div class="category-items category-container">
            <?php foreach ($categories as $category): ?>
                <div class="category-item">
                    <a href="<?= $block->escapeUrl($category['url']) ?>">
                        <div class="category-image">
                            <?php if ($category['image']): ?>
                                <div class="image-wrapper">
                                    <img src="<?= $block->escapeUrl($category['image']) ?>"
                                         alt="<?= $block->escapeHtmlAttr($category['name']) ?>"
                                         loading="lazy"/>
                                </div>
                            <?php else: ?>
                                <div class="no-image">
                                    <?= __('No Image') ?>
                                </div>
                            <?php endif; ?>
                            <div class="category-info">
                                <div class="category-title-wrapper">
                                    <h3 class="category-title"><?= $block->escapeHtml($category['name']) ?></h3>
                                </div>
                                <div class="product-count-wrapper">
                                    <span class="product-count"><?= $block->escapeHtml($category['product_count']) ?> <?= __('Products') ?></span>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    </div>
</section>
<?php endif; ?>