<?php 

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $name = '';
       $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $url = $block->getUrl('*/*/*/'
            );

    if($params = $this->getRequest()->getParams()){
      $name = isset($params['pr'])?$params['pr']:'';
      $params['to'] = isset($params['to'])?$params['to']:date("Y-m-d");
      $params['from'] = isset($params['from'])?$params['from']:date("Y-m-d",strtotime("-1 month"));
      $endate =str_replace( '.', '-', $params['to'] ); 
      $startdate =str_replace( '.', '-', $params['from'] ); 
    }
    else{
        $startdate = date("Y-m-d",strtotime("-1 month"));
        $endate = date("Y-m-d");
        $name = '';
    }
    

    $resourceCollection =  $objectManager->create('Lof\Rma\Model\ResourceModel\Item\Collection')
           ->addFieldToFilter(
                    'main_table.reason_id',
                    array('notnull' => true)
                )
            ->setDateColumnFilter('created_at')
            ->addDateFromFilter($startdate)
            ->addDateToFilter( $endate)
            ->_getReasonSelectedColumns($name);
            if($name){
            $resourceCollection->addFieldToFilter('product.value', array('like' => '%' . $name . '%'));
            }
   
    $collection = $resourceCollection->getData();  

?>
<div class = 'reasonchart'>

                <div class="filter">
                    <label><?php echo __("From");?></label>

                    <input name="datefrom" id="datefrom"  value="<?php echo $startdate ?>" type="text">
                    <label><?php echo __("To");?></label>
                    <input name="dateto" id="dateto"  value="<?php echo $endate ?>" type="text">
                    <label><?php echo __("Product");?></label>
                    <input name="pr" id="pr"  value="<?php echo $name ?>" type="text">
                    <button type="button" id='filter' ><?php echo __("Filter");?></button>
                    <button type="button" id='reset_product_filter' ><?php echo __("Reset Product Filter");?></button>
                    
                </div>


    <script type="text/javascript">
        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
            $('#datefrom').datepicker({
                    prevText: '&#x3c;zurück', prevStatus: '',
                    prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                    nextText: 'Vor&#x3e;', nextStatus: '',
                    nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                        'July', 'August', 'September', 'October', 'November', 'December'],
                    monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                    dayNamesShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    showMonthAfterYear: false,
                    dateFormat: 'yy.mm.dd '
                }
            );
            $('#dateto').datepicker({
                prevText: '&#x3c;zurück', prevStatus: '',
                prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                nextText: 'Vor&#x3e;', nextStatus: '',
                nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'],
                monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                dayNamesShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                showMonthAfterYear: false,
                dateFormat: 'yy.mm.dd'
            });
            var t = $('#dateto').val();
            var fr = $('#datefrom').val();
            var pr = $('#pr').val();
            $("#dateto").change(function () {
                t = $('#dateto').val();
            });
            $("#datefrom").change(function () {
                fr = $('#datefrom').val();
            });
            $('#pr').change(function () {
                pr = $('#pr').val();
            });
            $("#filter").click(function () {
                window.location.href = '<?php echo $url ?>?from=' + fr + '&to=' + t + '&pr=' + pr;
            });
            $("#reset_product_filter").click(function () {
                $('#pr').val('');
                window.location.href = '<?php echo $url ?>?from=' + fr + '&to=' + t + '&pr=' + '';
            });
        });
    </script>

<?php
if(count($collection)>0){
?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages': ['corechart']});
        google.charts.setOnLoadCallback(drawVisualization);
        var d = [];
        d.push(['Reason(Product)', 'Total RMA', 'Total Request', 'Total Return']);
        <?php
        if($name){
        foreach ($collection as $value) {
        if (!$value['total_returned_cnt'])
            $value['total_returned_cnt'] = 0;
        ?>
        d.push(["<?php echo $value['reason_name'] . '-' . $value['product_name'] ?>",<?php
            echo $value['total_rma_cnt'] ?>,<?php echo $value['total_requested_cnt'] ?>,<?php echo $value['total_returned_cnt'] ?>]);


        <?php
        }
        }
        else{
        foreach ($collection as $value) {
        if (!$value['total_returned_cnt'])
            $value['total_returned_cnt'] = 0;
        ?>
        d.push(["<?php echo $value['reason_name'] ?>",<?php
            echo $value['total_rma_cnt'] ?>,<?php echo $value['total_requested_cnt'] ?>,<?php echo $value['total_returned_cnt'] ?>]);


        <?php
        }
        }
        ?>

        function drawVisualization() {
            // Some raw data (not necessarily accurate)
            var data = google.visualization.arrayToDataTable(d);

            var options = {
                title: '<?php echo __("RMA Reason Report");?>',
                vAxis: {title: '<?php echo __("Number");?>'},
                hAxis: {title: '<?php echo __("Reason");?>'},
                seriesType: 'bars',
                /* series: {5: {type: 'line'}}*/
            };

            var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));

            google.visualization.events.addListener(chart, 'ready', function () {
                var uri = chart.getImageURI();

                var imgLink = document.getElementById('export_link');
                imgLink.setAttribute('href', uri);
            });

            chart.draw(data, options);
        }
    </script>

<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;" download><?php echo __("Save chart as an image");?></a>
<div id="chart_div" style="width: 100%; height: 400px;"></div>
<?php
}
?>
</div>